// AUTO-GENERATED from legacy/wails/internal/config/themes.go by macos/scripts/gen_themes.py.
// Do not edit by hand; rerun `make -C macos themes` after changing the Go themes.

use crate::models::{Theme, ThemeColors};

/// The built-in themes, in catalogue order.
pub fn built_in_themes() -> Vec<Theme> {
    vec![
        Theme {
            name: "catppuccin".into(),
            display_name: "Catppuccin".into(),
            dark: ThemeColors {
                bg_primary: "#1e1e2e".into(),
                bg_secondary: "#181825".into(),
                bg_surface: "#313244".into(),
                bg_hover: "#45475a".into(),
                text_primary: "#cdd6f4".into(),
                text_secondary: "#a6adc8".into(),
                text_muted: "#6c7086".into(),
                accent: "#89b4fa".into(),
                accent_hover: "#74c7ec".into(),
                border: "#45475a".into(),
                danger: "#f38ba8".into(),
                success: "#a6e3a1".into(),
                warning: "#f9e2af".into(),
                tab_active: "#1e1e2e".into(),
                tab_inactive: "#181825".into(),
                badge_color: "#f9e2af".into(),
                scrollbar_track: "#181825".into(),
                scrollbar_thumb: "#45475a".into(),
            },
            light: ThemeColors {
                bg_primary: "#eff1f5".into(),
                bg_secondary: "#e6e9ef".into(),
                bg_surface: "#ccd0da".into(),
                bg_hover: "#bcc0cc".into(),
                text_primary: "#4c4f69".into(),
                text_secondary: "#5c5f77".into(),
                text_muted: "#9ca0b0".into(),
                accent: "#1e66f5".into(),
                accent_hover: "#209fb5".into(),
                border: "#bcc0cc".into(),
                danger: "#d20f39".into(),
                success: "#40a02b".into(),
                warning: "#df8e1d".into(),
                tab_active: "#eff1f5".into(),
                tab_inactive: "#e6e9ef".into(),
                badge_color: "#df8e1d".into(),
                scrollbar_track: "#e6e9ef".into(),
                scrollbar_thumb: "#bcc0cc".into(),
            },
            built_in: true,
        },
        Theme {
            name: "nord".into(),
            display_name: "Nord".into(),
            dark: ThemeColors {
                bg_primary: "#2e3440".into(),
                bg_secondary: "#272c36".into(),
                bg_surface: "#3b4252".into(),
                bg_hover: "#434c5e".into(),
                text_primary: "#d8dee9".into(),
                text_secondary: "#c0c8d8".into(),
                text_muted: "#616e88".into(),
                accent: "#88c0d0".into(),
                accent_hover: "#8fbcbb".into(),
                border: "#434c5e".into(),
                danger: "#bf616a".into(),
                success: "#a3be8c".into(),
                warning: "#ebcb8b".into(),
                tab_active: "#2e3440".into(),
                tab_inactive: "#272c36".into(),
                badge_color: "#ebcb8b".into(),
                scrollbar_track: "#272c36".into(),
                scrollbar_thumb: "#434c5e".into(),
            },
            light: ThemeColors {
                bg_primary: "#eceff4".into(),
                bg_secondary: "#e5e9f0".into(),
                bg_surface: "#d8dee9".into(),
                bg_hover: "#c0c8d8".into(),
                text_primary: "#2e3440".into(),
                text_secondary: "#3b4252".into(),
                text_muted: "#7b88a1".into(),
                accent: "#5e81ac".into(),
                accent_hover: "#81a1c1".into(),
                border: "#c0c8d8".into(),
                danger: "#bf616a".into(),
                success: "#a3be8c".into(),
                warning: "#d08770".into(),
                tab_active: "#eceff4".into(),
                tab_inactive: "#e5e9f0".into(),
                badge_color: "#d08770".into(),
                scrollbar_track: "#e5e9f0".into(),
                scrollbar_thumb: "#c0c8d8".into(),
            },
            built_in: true,
        },
        Theme {
            name: "tokyo-night".into(),
            display_name: "Tokyo Night".into(),
            dark: ThemeColors {
                bg_primary: "#1a1b26".into(),
                bg_secondary: "#16161e".into(),
                bg_surface: "#24283b".into(),
                bg_hover: "#33467c".into(),
                text_primary: "#c0caf5".into(),
                text_secondary: "#a9b1d6".into(),
                text_muted: "#565f89".into(),
                accent: "#7aa2f7".into(),
                accent_hover: "#7dcfff".into(),
                border: "#33467c".into(),
                danger: "#f7768e".into(),
                success: "#9ece6a".into(),
                warning: "#e0af68".into(),
                tab_active: "#1a1b26".into(),
                tab_inactive: "#16161e".into(),
                badge_color: "#e0af68".into(),
                scrollbar_track: "#16161e".into(),
                scrollbar_thumb: "#33467c".into(),
            },
            light: ThemeColors {
                bg_primary: "#d5d6db".into(),
                bg_secondary: "#cbccd1".into(),
                bg_surface: "#b4b5b9".into(),
                bg_hover: "#9699a3".into(),
                text_primary: "#343b58".into(),
                text_secondary: "#4c505e".into(),
                text_muted: "#8990b3".into(),
                accent: "#34548a".into(),
                accent_hover: "#166775".into(),
                border: "#9699a3".into(),
                danger: "#8c4351".into(),
                success: "#485e30".into(),
                warning: "#8f5e15".into(),
                tab_active: "#d5d6db".into(),
                tab_inactive: "#cbccd1".into(),
                badge_color: "#8f5e15".into(),
                scrollbar_track: "#cbccd1".into(),
                scrollbar_thumb: "#9699a3".into(),
            },
            built_in: true,
        },
        Theme {
            name: "gruvbox".into(),
            display_name: "Gruvbox".into(),
            dark: ThemeColors {
                bg_primary: "#282828".into(),
                bg_secondary: "#1d2021".into(),
                bg_surface: "#3c3836".into(),
                bg_hover: "#504945".into(),
                text_primary: "#ebdbb2".into(),
                text_secondary: "#d5c4a1".into(),
                text_muted: "#7c6f64".into(),
                accent: "#83a598".into(),
                accent_hover: "#8ec07c".into(),
                border: "#504945".into(),
                danger: "#fb4934".into(),
                success: "#b8bb26".into(),
                warning: "#fabd2f".into(),
                tab_active: "#282828".into(),
                tab_inactive: "#1d2021".into(),
                badge_color: "#fabd2f".into(),
                scrollbar_track: "#1d2021".into(),
                scrollbar_thumb: "#504945".into(),
            },
            light: ThemeColors {
                bg_primary: "#fbf1c7".into(),
                bg_secondary: "#f2e5bc".into(),
                bg_surface: "#ebdbb2".into(),
                bg_hover: "#d5c4a1".into(),
                text_primary: "#3c3836".into(),
                text_secondary: "#504945".into(),
                text_muted: "#928374".into(),
                accent: "#427b58".into(),
                accent_hover: "#79740e".into(),
                border: "#d5c4a1".into(),
                danger: "#9d0006".into(),
                success: "#79740e".into(),
                warning: "#b57614".into(),
                tab_active: "#fbf1c7".into(),
                tab_inactive: "#f2e5bc".into(),
                badge_color: "#b57614".into(),
                scrollbar_track: "#f2e5bc".into(),
                scrollbar_thumb: "#d5c4a1".into(),
            },
            built_in: true,
        },
        Theme {
            name: "dracula".into(),
            display_name: "Dracula".into(),
            dark: ThemeColors {
                bg_primary: "#282a36".into(),
                bg_secondary: "#21222c".into(),
                bg_surface: "#44475a".into(),
                bg_hover: "#555972".into(),
                text_primary: "#f8f8f2".into(),
                text_secondary: "#d4d4d4".into(),
                text_muted: "#6272a4".into(),
                accent: "#bd93f9".into(),
                accent_hover: "#ff79c6".into(),
                border: "#44475a".into(),
                danger: "#ff5555".into(),
                success: "#50fa7b".into(),
                warning: "#f1fa8c".into(),
                tab_active: "#282a36".into(),
                tab_inactive: "#21222c".into(),
                badge_color: "#f1fa8c".into(),
                scrollbar_track: "#21222c".into(),
                scrollbar_thumb: "#44475a".into(),
            },
            light: ThemeColors {
                bg_primary: "#f8f8f2".into(),
                bg_secondary: "#f0f0e8".into(),
                bg_surface: "#e0e0d4".into(),
                bg_hover: "#d0d0c4".into(),
                text_primary: "#282a36".into(),
                text_secondary: "#44475a".into(),
                text_muted: "#8791b5".into(),
                accent: "#7c3aed".into(),
                accent_hover: "#d6409f".into(),
                border: "#d0d0c4".into(),
                danger: "#dc2626".into(),
                success: "#16a34a".into(),
                warning: "#ca8a04".into(),
                tab_active: "#f8f8f2".into(),
                tab_inactive: "#f0f0e8".into(),
                badge_color: "#ca8a04".into(),
                scrollbar_track: "#f0f0e8".into(),
                scrollbar_thumb: "#d0d0c4".into(),
            },
            built_in: true,
        },
        Theme {
            name: "one-dark".into(),
            display_name: "One Dark".into(),
            dark: ThemeColors {
                bg_primary: "#282c34".into(),
                bg_secondary: "#21252b".into(),
                bg_surface: "#353b45".into(),
                bg_hover: "#3e4452".into(),
                text_primary: "#abb2bf".into(),
                text_secondary: "#9da5b4".into(),
                text_muted: "#636d83".into(),
                accent: "#61afef".into(),
                accent_hover: "#56b6c2".into(),
                border: "#3e4452".into(),
                danger: "#e06c75".into(),
                success: "#98c379".into(),
                warning: "#e5c07b".into(),
                tab_active: "#282c34".into(),
                tab_inactive: "#21252b".into(),
                badge_color: "#e5c07b".into(),
                scrollbar_track: "#21252b".into(),
                scrollbar_thumb: "#3e4452".into(),
            },
            light: ThemeColors {
                bg_primary: "#fafafa".into(),
                bg_secondary: "#f0f0f0".into(),
                bg_surface: "#e0e0e0".into(),
                bg_hover: "#d0d0d0".into(),
                text_primary: "#383a42".into(),
                text_secondary: "#4f525e".into(),
                text_muted: "#a0a1a7".into(),
                accent: "#4078f2".into(),
                accent_hover: "#0184bc".into(),
                border: "#d0d0d0".into(),
                danger: "#e45649".into(),
                success: "#50a14f".into(),
                warning: "#c18401".into(),
                tab_active: "#fafafa".into(),
                tab_inactive: "#f0f0f0".into(),
                badge_color: "#c18401".into(),
                scrollbar_track: "#f0f0f0".into(),
                scrollbar_thumb: "#d0d0d0".into(),
            },
            built_in: true,
        },
        Theme {
            name: "catppuccin-macchiato".into(),
            display_name: "Catppuccin Macchiato".into(),
            dark: ThemeColors {
                bg_primary: "#24273a".into(),
                bg_secondary: "#1e2030".into(),
                bg_surface: "#363a4f".into(),
                bg_hover: "#494d64".into(),
                text_primary: "#cad3f5".into(),
                text_secondary: "#a5adcb".into(),
                text_muted: "#6e738d".into(),
                accent: "#8aadf4".into(),
                accent_hover: "#91d7e3".into(),
                border: "#494d64".into(),
                danger: "#ed8796".into(),
                success: "#a6da95".into(),
                warning: "#eed49f".into(),
                tab_active: "#24273a".into(),
                tab_inactive: "#1e2030".into(),
                badge_color: "#eed49f".into(),
                scrollbar_track: "#1e2030".into(),
                scrollbar_thumb: "#494d64".into(),
            },
            light: ThemeColors {
                bg_primary: "#eff1f5".into(),
                bg_secondary: "#e6e9ef".into(),
                bg_surface: "#ccd0da".into(),
                bg_hover: "#bcc0cc".into(),
                text_primary: "#4c4f69".into(),
                text_secondary: "#5c5f77".into(),
                text_muted: "#9ca0b0".into(),
                accent: "#1e66f5".into(),
                accent_hover: "#209fb5".into(),
                border: "#bcc0cc".into(),
                danger: "#d20f39".into(),
                success: "#40a02b".into(),
                warning: "#df8e1d".into(),
                tab_active: "#eff1f5".into(),
                tab_inactive: "#e6e9ef".into(),
                badge_color: "#df8e1d".into(),
                scrollbar_track: "#e6e9ef".into(),
                scrollbar_thumb: "#bcc0cc".into(),
            },
            built_in: true,
        },
        Theme {
            name: "solarized".into(),
            display_name: "Solarized".into(),
            dark: ThemeColors {
                bg_primary: "#002b36".into(),
                bg_secondary: "#073642".into(),
                bg_surface: "#094959".into(),
                bg_hover: "#1a5c6e".into(),
                text_primary: "#839496".into(),
                text_secondary: "#93a1a1".into(),
                text_muted: "#586e75".into(),
                accent: "#268bd2".into(),
                accent_hover: "#2aa198".into(),
                border: "#1a5c6e".into(),
                danger: "#dc322f".into(),
                success: "#859900".into(),
                warning: "#b58900".into(),
                tab_active: "#002b36".into(),
                tab_inactive: "#073642".into(),
                badge_color: "#b58900".into(),
                scrollbar_track: "#073642".into(),
                scrollbar_thumb: "#1a5c6e".into(),
            },
            light: ThemeColors {
                bg_primary: "#fdf6e3".into(),
                bg_secondary: "#eee8d5".into(),
                bg_surface: "#ddd6c1".into(),
                bg_hover: "#ccc5af".into(),
                text_primary: "#657b83".into(),
                text_secondary: "#586e75".into(),
                text_muted: "#93a1a1".into(),
                accent: "#268bd2".into(),
                accent_hover: "#2aa198".into(),
                border: "#ccc5af".into(),
                danger: "#dc322f".into(),
                success: "#859900".into(),
                warning: "#b58900".into(),
                tab_active: "#fdf6e3".into(),
                tab_inactive: "#eee8d5".into(),
                badge_color: "#b58900".into(),
                scrollbar_track: "#eee8d5".into(),
                scrollbar_thumb: "#ccc5af".into(),
            },
            built_in: true,
        },
        Theme {
            name: "everforest".into(),
            display_name: "Everforest".into(),
            dark: ThemeColors {
                bg_primary: "#2d353b".into(),
                bg_secondary: "#272e33".into(),
                bg_surface: "#343f44".into(),
                bg_hover: "#3d484d".into(),
                text_primary: "#d3c6aa".into(),
                text_secondary: "#c5b89a".into(),
                text_muted: "#7a8478".into(),
                accent: "#a7c080".into(),
                accent_hover: "#83c092".into(),
                border: "#3d484d".into(),
                danger: "#e67e80".into(),
                success: "#a7c080".into(),
                warning: "#dbbc7f".into(),
                tab_active: "#2d353b".into(),
                tab_inactive: "#272e33".into(),
                badge_color: "#dbbc7f".into(),
                scrollbar_track: "#272e33".into(),
                scrollbar_thumb: "#3d484d".into(),
            },
            light: ThemeColors {
                bg_primary: "#fdf6e3".into(),
                bg_secondary: "#f4f0d9".into(),
                bg_surface: "#e5dfc5".into(),
                bg_hover: "#d8d3ba".into(),
                text_primary: "#5c6a72".into(),
                text_secondary: "#708089".into(),
                text_muted: "#a6b0a0".into(),
                accent: "#8da101".into(),
                accent_hover: "#35a77c".into(),
                border: "#d8d3ba".into(),
                danger: "#f85552".into(),
                success: "#8da101".into(),
                warning: "#dfa000".into(),
                tab_active: "#fdf6e3".into(),
                tab_inactive: "#f4f0d9".into(),
                badge_color: "#dfa000".into(),
                scrollbar_track: "#f4f0d9".into(),
                scrollbar_thumb: "#d8d3ba".into(),
            },
            built_in: true,
        },
        Theme {
            name: "ayu".into(),
            display_name: "Ayu".into(),
            dark: ThemeColors {
                bg_primary: "#0b0e14".into(),
                bg_secondary: "#0d1017".into(),
                bg_surface: "#11151c".into(),
                bg_hover: "#1a1f29".into(),
                text_primary: "#bfbdb6".into(),
                text_secondary: "#acaaa1".into(),
                text_muted: "#565b66".into(),
                accent: "#e6b450".into(),
                accent_hover: "#ffb454".into(),
                border: "#1a1f29".into(),
                danger: "#d95757".into(),
                success: "#7fd962".into(),
                warning: "#e6b450".into(),
                tab_active: "#0b0e14".into(),
                tab_inactive: "#0d1017".into(),
                badge_color: "#e6b450".into(),
                scrollbar_track: "#0d1017".into(),
                scrollbar_thumb: "#1a1f29".into(),
            },
            light: ThemeColors {
                bg_primary: "#fcfcfc".into(),
                bg_secondary: "#f3f3f3".into(),
                bg_surface: "#e7e8e9".into(),
                bg_hover: "#d8d9da".into(),
                text_primary: "#5c6166".into(),
                text_secondary: "#787b80".into(),
                text_muted: "#abb0b6".into(),
                accent: "#f2ae49".into(),
                accent_hover: "#ff9940".into(),
                border: "#d8d9da".into(),
                danger: "#e65050".into(),
                success: "#86b300".into(),
                warning: "#f2ae49".into(),
                tab_active: "#fcfcfc".into(),
                tab_inactive: "#f3f3f3".into(),
                badge_color: "#f2ae49".into(),
                scrollbar_track: "#f3f3f3".into(),
                scrollbar_thumb: "#d8d9da".into(),
            },
            built_in: true,
        },
        Theme {
            name: "kanagawa".into(),
            display_name: "Kanagawa".into(),
            dark: ThemeColors {
                bg_primary: "#1f1f28".into(),
                bg_secondary: "#16161d".into(),
                bg_surface: "#2a2a37".into(),
                bg_hover: "#363646".into(),
                text_primary: "#dcd7ba".into(),
                text_secondary: "#c8c093".into(),
                text_muted: "#727169".into(),
                accent: "#7e9cd8".into(),
                accent_hover: "#7fb4ca".into(),
                border: "#363646".into(),
                danger: "#e82424".into(),
                success: "#98bb6c".into(),
                warning: "#e6c384".into(),
                tab_active: "#1f1f28".into(),
                tab_inactive: "#16161d".into(),
                badge_color: "#e6c384".into(),
                scrollbar_track: "#16161d".into(),
                scrollbar_thumb: "#363646".into(),
            },
            light: ThemeColors {
                bg_primary: "#f2ecbc".into(),
                bg_secondary: "#e7dba0".into(),
                bg_surface: "#d9cea6".into(),
                bg_hover: "#c9b97c".into(),
                text_primary: "#545464".into(),
                text_secondary: "#625e5a".into(),
                text_muted: "#8a8980".into(),
                accent: "#4d699b".into(),
                accent_hover: "#5a7785".into(),
                border: "#c9b97c".into(),
                danger: "#c84053".into(),
                success: "#6f894e".into(),
                warning: "#cc8c3c".into(),
                tab_active: "#f2ecbc".into(),
                tab_inactive: "#e7dba0".into(),
                badge_color: "#cc8c3c".into(),
                scrollbar_track: "#e7dba0".into(),
                scrollbar_thumb: "#c9b97c".into(),
            },
            built_in: true,
        },
        Theme {
            name: "matrix".into(),
            display_name: "Matrix".into(),
            dark: ThemeColors {
                bg_primary: "#0d0d0d".into(),
                bg_secondary: "#080808".into(),
                bg_surface: "#1a1a1a".into(),
                bg_hover: "#262626".into(),
                text_primary: "#00ff41".into(),
                text_secondary: "#00cc33".into(),
                text_muted: "#338033".into(),
                accent: "#00ff41".into(),
                accent_hover: "#33ff66".into(),
                border: "#1a3a1a".into(),
                danger: "#ff3333".into(),
                success: "#00ff41".into(),
                warning: "#ccff00".into(),
                tab_active: "#0d0d0d".into(),
                tab_inactive: "#080808".into(),
                badge_color: "#ccff00".into(),
                scrollbar_track: "#080808".into(),
                scrollbar_thumb: "#1a3a1a".into(),
            },
            light: ThemeColors {
                bg_primary: "#f0fff0".into(),
                bg_secondary: "#e0f5e0".into(),
                bg_surface: "#c8e6c8".into(),
                bg_hover: "#b0d9b0".into(),
                text_primary: "#0a3d0a".into(),
                text_secondary: "#1a5c1a".into(),
                text_muted: "#6b9e6b".into(),
                accent: "#008f11".into(),
                accent_hover: "#00b318".into(),
                border: "#b0d9b0".into(),
                danger: "#cc2222".into(),
                success: "#008f11".into(),
                warning: "#7a9900".into(),
                tab_active: "#f0fff0".into(),
                tab_inactive: "#e0f5e0".into(),
                badge_color: "#7a9900".into(),
                scrollbar_track: "#e0f5e0".into(),
                scrollbar_thumb: "#b0d9b0".into(),
            },
            built_in: true,
        },
        Theme {
            name: "rose-pine".into(),
            display_name: "Rosé Pine".into(),
            dark: ThemeColors {
                bg_primary: "#191724".into(),
                bg_secondary: "#1f1d2e".into(),
                bg_surface: "#26233a".into(),
                bg_hover: "#2a283e".into(),
                text_primary: "#e0def4".into(),
                text_secondary: "#c4a7e7".into(),
                text_muted: "#6e6a86".into(),
                accent: "#c4a7e7".into(),
                accent_hover: "#ebbcba".into(),
                border: "#2a283e".into(),
                danger: "#eb6f92".into(),
                success: "#31748f".into(),
                warning: "#f6c177".into(),
                tab_active: "#191724".into(),
                tab_inactive: "#1f1d2e".into(),
                badge_color: "#f6c177".into(),
                scrollbar_track: "#1f1d2e".into(),
                scrollbar_thumb: "#2a283e".into(),
            },
            light: ThemeColors {
                bg_primary: "#faf4ed".into(),
                bg_secondary: "#fffaf3".into(),
                bg_surface: "#f2e9e1".into(),
                bg_hover: "#dfdad9".into(),
                text_primary: "#575279".into(),
                text_secondary: "#907aa9".into(),
                text_muted: "#9893a5".into(),
                accent: "#907aa9".into(),
                accent_hover: "#d7827e".into(),
                border: "#dfdad9".into(),
                danger: "#b4637a".into(),
                success: "#286983".into(),
                warning: "#ea9d34".into(),
                tab_active: "#faf4ed".into(),
                tab_inactive: "#fffaf3".into(),
                badge_color: "#ea9d34".into(),
                scrollbar_track: "#fffaf3".into(),
                scrollbar_thumb: "#dfdad9".into(),
            },
            built_in: true,
        },
        Theme {
            name: "monokai".into(),
            display_name: "Monokai".into(),
            dark: ThemeColors {
                bg_primary: "#272822".into(),
                bg_secondary: "#1e1f1c".into(),
                bg_surface: "#3e3d32".into(),
                bg_hover: "#4e4d42".into(),
                text_primary: "#f8f8f2".into(),
                text_secondary: "#e0e0d8".into(),
                text_muted: "#75715e".into(),
                accent: "#66d9ef".into(),
                accent_hover: "#a6e22e".into(),
                border: "#4e4d42".into(),
                danger: "#f92672".into(),
                success: "#a6e22e".into(),
                warning: "#e6db74".into(),
                tab_active: "#272822".into(),
                tab_inactive: "#1e1f1c".into(),
                badge_color: "#e6db74".into(),
                scrollbar_track: "#1e1f1c".into(),
                scrollbar_thumb: "#4e4d42".into(),
            },
            light: ThemeColors {
                bg_primary: "#fafafa".into(),
                bg_secondary: "#f0f0ec".into(),
                bg_surface: "#e0e0dc".into(),
                bg_hover: "#d0d0cc".into(),
                text_primary: "#272822".into(),
                text_secondary: "#49483e".into(),
                text_muted: "#9e9d89".into(),
                accent: "#00a2c4".into(),
                accent_hover: "#669900".into(),
                border: "#d0d0cc".into(),
                danger: "#d31b5f".into(),
                success: "#669900".into(),
                warning: "#c4a500".into(),
                tab_active: "#fafafa".into(),
                tab_inactive: "#f0f0ec".into(),
                badge_color: "#c4a500".into(),
                scrollbar_track: "#f0f0ec".into(),
                scrollbar_thumb: "#d0d0cc".into(),
            },
            built_in: true,
        },
        Theme {
            name: "catppuccin-frappe".into(),
            display_name: "Catppuccin Frappé".into(),
            dark: ThemeColors {
                bg_primary: "#303446".into(),
                bg_secondary: "#292c3c".into(),
                bg_surface: "#414559".into(),
                bg_hover: "#51576d".into(),
                text_primary: "#c6d0f5".into(),
                text_secondary: "#b5bfe2".into(),
                text_muted: "#949cb8".into(),
                accent: "#8da4e2".into(),
                accent_hover: "#99b2ec".into(),
                border: "#414559".into(),
                danger: "#e78284".into(),
                success: "#a6d189".into(),
                warning: "#e5c890".into(),
                tab_active: "#303446".into(),
                tab_inactive: "#292c3c".into(),
                badge_color: "#e5c890".into(),
                scrollbar_track: "#292c3c".into(),
                scrollbar_thumb: "#51576d".into(),
            },
            light: ThemeColors {
                bg_primary: "#eff1f5".into(),
                bg_secondary: "#e6e9ef".into(),
                bg_surface: "#ccd0da".into(),
                bg_hover: "#bcc0cc".into(),
                text_primary: "#4c4f69".into(),
                text_secondary: "#5c5f77".into(),
                text_muted: "#9ca0b0".into(),
                accent: "#1e66f5".into(),
                accent_hover: "#2c74ff".into(),
                border: "#bcc0cc".into(),
                danger: "#d20f39".into(),
                success: "#40a02b".into(),
                warning: "#df8e1d".into(),
                tab_active: "#eff1f5".into(),
                tab_inactive: "#e6e9ef".into(),
                badge_color: "#df8e1d".into(),
                scrollbar_track: "#e6e9ef".into(),
                scrollbar_thumb: "#bcc0cc".into(),
            },
            built_in: true,
        },
        Theme {
            name: "night-owl".into(),
            display_name: "Night Owl".into(),
            dark: ThemeColors {
                bg_primary: "#011627".into(),
                bg_secondary: "#01111d".into(),
                bg_surface: "#1d3b53".into(),
                bg_hover: "#2a4a6b".into(),
                text_primary: "#d6deeb".into(),
                text_secondary: "#b8c4d4".into(),
                text_muted: "#637777".into(),
                accent: "#82aaff".into(),
                accent_hover: "#9ebfff".into(),
                border: "#1d3b53".into(),
                danger: "#ef5350".into(),
                success: "#c5e478".into(),
                warning: "#ecc48d".into(),
                tab_active: "#011627".into(),
                tab_inactive: "#01111d".into(),
                badge_color: "#ecc48d".into(),
                scrollbar_track: "#01111d".into(),
                scrollbar_thumb: "#1d3b53".into(),
            },
            light: ThemeColors {
                bg_primary: "#f0f0f0".into(),
                bg_secondary: "#e5e5e5".into(),
                bg_surface: "#d4d4d4".into(),
                bg_hover: "#c0c0c0".into(),
                text_primary: "#403f53".into(),
                text_secondary: "#575668".into(),
                text_muted: "#7a8181".into(),
                accent: "#4876d6".into(),
                accent_hover: "#5a88e8".into(),
                border: "#d4d4d4".into(),
                danger: "#de3d3b".into(),
                success: "#2aa298".into(),
                warning: "#c96765".into(),
                tab_active: "#f0f0f0".into(),
                tab_inactive: "#e5e5e5".into(),
                badge_color: "#c96765".into(),
                scrollbar_track: "#e5e5e5".into(),
                scrollbar_thumb: "#c0c0c0".into(),
            },
            built_in: true,
        },
        Theme {
            name: "synthwave-84".into(),
            display_name: "Synthwave '84".into(),
            dark: ThemeColors {
                bg_primary: "#262335".into(),
                bg_secondary: "#1e1a30".into(),
                bg_surface: "#34294f".into(),
                bg_hover: "#443566".into(),
                text_primary: "#ffffff".into(),
                text_secondary: "#e0d0f0".into(),
                text_muted: "#848bbd".into(),
                accent: "#36f9f6".into(),
                accent_hover: "#ff7edb".into(),
                border: "#495495".into(),
                danger: "#fe4450".into(),
                success: "#72f1b8".into(),
                warning: "#fede5d".into(),
                tab_active: "#262335".into(),
                tab_inactive: "#1e1a30".into(),
                badge_color: "#fede5d".into(),
                scrollbar_track: "#1e1a30".into(),
                scrollbar_thumb: "#495495".into(),
            },
            light: ThemeColors {
                bg_primary: "#fafafa".into(),
                bg_secondary: "#f0f0f0".into(),
                bg_surface: "#e0e0e0".into(),
                bg_hover: "#d0d0d0".into(),
                text_primary: "#262335".into(),
                text_secondary: "#3d3650".into(),
                text_muted: "#5c5c8a".into(),
                accent: "#00bcd4".into(),
                accent_hover: "#9c27b0".into(),
                border: "#e0e0e0".into(),
                danger: "#f44336".into(),
                success: "#4caf50".into(),
                warning: "#ff9800".into(),
                tab_active: "#fafafa".into(),
                tab_inactive: "#f0f0f0".into(),
                badge_color: "#ff9800".into(),
                scrollbar_track: "#f0f0f0".into(),
                scrollbar_thumb: "#d0d0d0".into(),
            },
            built_in: true,
        },
        Theme {
            name: "cobalt2".into(),
            display_name: "Cobalt2".into(),
            dark: ThemeColors {
                bg_primary: "#193549".into(),
                bg_secondary: "#132d3e".into(),
                bg_surface: "#1f4662".into(),
                bg_hover: "#2d5a7b".into(),
                text_primary: "#ffffff".into(),
                text_secondary: "#dde6ef".into(),
                text_muted: "#adb7c9".into(),
                accent: "#0088ff".into(),
                accent_hover: "#2affdf".into(),
                border: "#2d5a7b".into(),
                danger: "#ff0088".into(),
                success: "#9eff80".into(),
                warning: "#ffc600".into(),
                tab_active: "#193549".into(),
                tab_inactive: "#132d3e".into(),
                badge_color: "#ffc600".into(),
                scrollbar_track: "#132d3e".into(),
                scrollbar_thumb: "#2d5a7b".into(),
            },
            light: ThemeColors {
                bg_primary: "#ffffff".into(),
                bg_secondary: "#f4f6f8".into(),
                bg_surface: "#e8ecf0".into(),
                bg_hover: "#d3dae3".into(),
                text_primary: "#193549".into(),
                text_secondary: "#2e4a5e".into(),
                text_muted: "#5c6b7d".into(),
                accent: "#0066cc".into(),
                accent_hover: "#00acc1".into(),
                border: "#d3dae3".into(),
                danger: "#e91e63".into(),
                success: "#4caf50".into(),
                warning: "#ff9800".into(),
                tab_active: "#ffffff".into(),
                tab_inactive: "#f4f6f8".into(),
                badge_color: "#ff9800".into(),
                scrollbar_track: "#f4f6f8".into(),
                scrollbar_thumb: "#d3dae3".into(),
            },
            built_in: true,
        },
        Theme {
            name: "github".into(),
            display_name: "GitHub".into(),
            dark: ThemeColors {
                bg_primary: "#0d1117".into(),
                bg_secondary: "#090c10".into(),
                bg_surface: "#161b22".into(),
                bg_hover: "#30363d".into(),
                text_primary: "#c9d1d9".into(),
                text_secondary: "#b1bac4".into(),
                text_muted: "#8b949e".into(),
                accent: "#58a6ff".into(),
                accent_hover: "#39c5cf".into(),
                border: "#30363d".into(),
                danger: "#f85149".into(),
                success: "#3fb950".into(),
                warning: "#e3b341".into(),
                tab_active: "#0d1117".into(),
                tab_inactive: "#090c10".into(),
                badge_color: "#e3b341".into(),
                scrollbar_track: "#090c10".into(),
                scrollbar_thumb: "#30363d".into(),
            },
            light: ThemeColors {
                bg_primary: "#ffffff".into(),
                bg_secondary: "#f6f8fa".into(),
                bg_surface: "#f6f8fa".into(),
                bg_hover: "#d0d7de".into(),
                text_primary: "#24292f".into(),
                text_secondary: "#3b424a".into(),
                text_muted: "#57606a".into(),
                accent: "#0969da".into(),
                accent_hover: "#1b7c83".into(),
                border: "#d0d7de".into(),
                danger: "#cf222e".into(),
                success: "#1a7f37".into(),
                warning: "#9a6700".into(),
                tab_active: "#ffffff".into(),
                tab_inactive: "#f6f8fa".into(),
                badge_color: "#9a6700".into(),
                scrollbar_track: "#f6f8fa".into(),
                scrollbar_thumb: "#d0d7de".into(),
            },
            built_in: true,
        },
        Theme {
            name: "palenight".into(),
            display_name: "Palenight".into(),
            dark: ThemeColors {
                bg_primary: "#292d3e".into(),
                bg_secondary: "#232738".into(),
                bg_surface: "#3a3f58".into(),
                bg_hover: "#4a4f6e".into(),
                text_primary: "#a6accd".into(),
                text_secondary: "#959bba".into(),
                text_muted: "#676e95".into(),
                accent: "#82aaff".into(),
                accent_hover: "#89ddff".into(),
                border: "#3a3f58".into(),
                danger: "#f07178".into(),
                success: "#c3e88d".into(),
                warning: "#ffcb6b".into(),
                tab_active: "#292d3e".into(),
                tab_inactive: "#232738".into(),
                badge_color: "#ffcb6b".into(),
                scrollbar_track: "#232738".into(),
                scrollbar_thumb: "#3a3f58".into(),
            },
            light: ThemeColors {
                bg_primary: "#fafafa".into(),
                bg_secondary: "#f0f0f0".into(),
                bg_surface: "#eef0f4".into(),
                bg_hover: "#dce0e8".into(),
                text_primary: "#292d3e".into(),
                text_secondary: "#3e4254".into(),
                text_muted: "#8796b0".into(),
                accent: "#4976eb".into(),
                accent_hover: "#00acc1".into(),
                border: "#dce0e8".into(),
                danger: "#e53935".into(),
                success: "#91b859".into(),
                warning: "#ffb300".into(),
                tab_active: "#fafafa".into(),
                tab_inactive: "#f0f0f0".into(),
                badge_color: "#ffb300".into(),
                scrollbar_track: "#f0f0f0".into(),
                scrollbar_thumb: "#dce0e8".into(),
            },
            built_in: true,
        },
        Theme {
            name: "zenburn".into(),
            display_name: "Zenburn".into(),
            dark: ThemeColors {
                bg_primary: "#3f3f3f".into(),
                bg_secondary: "#353535".into(),
                bg_surface: "#4f4f4f".into(),
                bg_hover: "#5f5f5f".into(),
                text_primary: "#dcdccc".into(),
                text_secondary: "#c8c8b8".into(),
                text_muted: "#9f9f9f".into(),
                accent: "#8cd0d3".into(),
                accent_hover: "#93e0e3".into(),
                border: "#5f5f5f".into(),
                danger: "#cc9393".into(),
                success: "#7f9f7f".into(),
                warning: "#f0dfaf".into(),
                tab_active: "#3f3f3f".into(),
                tab_inactive: "#353535".into(),
                badge_color: "#f0dfaf".into(),
                scrollbar_track: "#353535".into(),
                scrollbar_thumb: "#5f5f5f".into(),
            },
            light: ThemeColors {
                bg_primary: "#ffffef".into(),
                bg_secondary: "#f5f5e5".into(),
                bg_surface: "#efefdf".into(),
                bg_hover: "#cfcfbf".into(),
                text_primary: "#3f3f3f".into(),
                text_secondary: "#525242".into(),
                text_muted: "#6f6f6f".into(),
                accent: "#5f7f8f".into(),
                accent_hover: "#5f8f8f".into(),
                border: "#cfcfbf".into(),
                danger: "#8f5f5f".into(),
                success: "#5f8f5f".into(),
                warning: "#8f8f5f".into(),
                tab_active: "#ffffef".into(),
                tab_inactive: "#f5f5e5".into(),
                badge_color: "#8f8f5f".into(),
                scrollbar_track: "#f5f5e5".into(),
                scrollbar_thumb: "#cfcfbf".into(),
            },
            built_in: true,
        },
    ]
}
