// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseTab(arg1) {
  return window['go']['main']['App']['CloseTab'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetSavedTabs() {
  return window['go']['main']['App']['GetSavedTabs']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTabLineRange(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTabLineRange'](arg1, arg2, arg3);
}

export function GetTabLines(arg1) {
  return window['go']['main']['App']['GetTabLines'](arg1);
}

export function GetTabTotalLines(arg1) {
  return window['go']['main']['App']['GetTabTotalLines'](arg1);
}

export function GetTabs() {
  return window['go']['main']['App']['GetTabs']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function OpenTab(arg1) {
  return window['go']['main']['App']['OpenTab'](arg1);
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function RevealInFileManager(arg1) {
  return window['go']['main']['App']['RevealInFileManager'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveTabOrder(arg1) {
  return window['go']['main']['App']['SaveTabOrder'](arg1);
}

export function SetTabProfile(arg1, arg2) {
  return window['go']['main']['App']['SetTabProfile'](arg1, arg2);
}

export function ValidateRegex(arg1) {
  return window['go']['main']['App']['ValidateRegex'](arg1);
}
