// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {tailer} from '../models';
import {main} from '../models';

export function CloseTab(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function GetProfile(arg1:string):Promise<config.Profile>;

export function GetSavedTabs():Promise<Array<config.TabState>>;

export function GetSettings():Promise<config.AppSettings>;

export function GetTabLineRange(arg1:string,arg2:number,arg3:number):Promise<Array<tailer.Line>>;

export function GetTabLines(arg1:string):Promise<Array<tailer.Line>>;

export function GetTabTotalLines(arg1:string):Promise<number>;

export function GetTabs():Promise<Array<main.TabInfo>>;

export function ListProfiles():Promise<Array<string>>;

export function OpenFileDialog():Promise<string>;

export function OpenTab(arg1:string):Promise<string>;

export function RenameProfile(arg1:string,arg2:string):Promise<void>;

export function SaveProfile(arg1:config.Profile):Promise<void>;

export function SaveSettings(arg1:config.AppSettings):Promise<void>;

export function SetTabProfile(arg1:string,arg2:string):Promise<void>;

export function ValidateRegex(arg1:string):Promise<string>;
