// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {tailer} from '../models';
import {main} from '../models';
import {ai} from '../models';

export function AddRecentFile(arg1:string):Promise<void>;

export function AskAI(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<string>;

export function ClearRecentFiles():Promise<void>;

export function CloseTab(arg1:string):Promise<void>;

export function CompleteCopilotAuth(arg1:string,arg2:number):Promise<boolean>;

export function DeleteCustomTheme(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function GenerateRulesProfile(arg1:string,arg2:string):Promise<config.Profile>;

export function GetAppVersion():Promise<string>;

export function GetProfile(arg1:string):Promise<config.Profile>;

export function GetRecentFiles():Promise<Array<string>>;

export function GetSavedTabs():Promise<Array<config.TabState>>;

export function GetSettings():Promise<config.AppSettings>;

export function GetTabLineRange(arg1:string,arg2:number,arg3:number):Promise<Array<tailer.Line>>;

export function GetTabLines(arg1:string):Promise<Array<tailer.Line>>;

export function GetTabTotalLines(arg1:string):Promise<number>;

export function GetTabs():Promise<Array<main.TabInfo>>;

export function GetTheme(arg1:string):Promise<config.Theme>;

export function ListProfiles():Promise<Array<string>>;

export function ListThemes():Promise<Array<config.Theme>>;

export function ManualCheckForUpdates():Promise<string>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function OpenTab(arg1:string):Promise<string>;

export function RefreshRecentMenu():Promise<void>;

export function RenameProfile(arg1:string,arg2:string):Promise<void>;

export function RevealInFileManager(arg1:string):Promise<void>;

export function SaveCustomTheme(arg1:config.Theme):Promise<void>;

export function SaveProfile(arg1:config.Profile):Promise<void>;

export function SaveSettings(arg1:config.AppSettings):Promise<void>;

export function SaveTabOrder(arg1:Array<config.TabState>):Promise<void>;

export function SetTabProfile(arg1:string,arg2:string):Promise<void>;

export function StartCopilotAuth():Promise<ai.DeviceCodeResponse>;

export function ValidateRegex(arg1:string):Promise<string>;
