package config

// ThemeColors defines all CSS variable values for a theme
type ThemeColors struct {
	BgPrimary    string `json:"bg-primary"`
	BgSecondary  string `json:"bg-secondary"`
	BgSurface    string `json:"bg-surface"`
	BgHover      string `json:"bg-hover"`
	TextPrimary  string `json:"text-primary"`
	TextSecondary string `json:"text-secondary"`
	TextMuted    string `json:"text-muted"`
	Accent       string `json:"accent"`
	AccentHover  string `json:"accent-hover"`
	Border       string `json:"border"`
	Danger       string `json:"danger"`
	Success      string `json:"success"`
	Warning      string `json:"warning"`
	TabActive    string `json:"tab-active"`
	TabInactive  string `json:"tab-inactive"`
	BadgeColor   string `json:"badge-color"`
	ScrollTrack  string `json:"scrollbar-track"`
	ScrollThumb  string `json:"scrollbar-thumb"`
}

// Theme defines a complete theme with dark and light variants
type Theme struct {
	Name        string      `json:"name"`
	DisplayName string      `json:"displayName"`
	Dark        ThemeColors `json:"dark"`
	Light       ThemeColors `json:"light"`
	BuiltIn     bool        `json:"builtIn"`
}

// BuiltInThemes returns all built-in themes
func BuiltInThemes() []Theme {
	return []Theme{
		catppuccinTheme(),
		catppuccinMacchiatoTheme(),
		catppuccinFrappeTheme(),
		nordTheme(),
		tokyoNightTheme(),
		gruvboxTheme(),
		draculaTheme(),
		oneDarkTheme(),
		solarizedTheme(),
		everforestTheme(),
		ayuTheme(),
		kanagawaTheme(),
		matrixTheme(),
		rosePineTheme(),
		monokaiTheme(),
		nightOwlTheme(),
		synthwave84Theme(),
		cobalt2Theme(),
		githubTheme(),
		palenightTheme(),
		zenburnTheme(),
	}
}

func catppuccinTheme() Theme {
	return Theme{
		Name:        "catppuccin",
		DisplayName: "Catppuccin",
		BuiltIn:     true,
		Dark: ThemeColors{
			BgPrimary:    "#1e1e2e",
			BgSecondary:  "#181825",
			BgSurface:    "#313244",
			BgHover:      "#45475a",
			TextPrimary:  "#cdd6f4",
			TextSecondary: "#a6adc8",
			TextMuted:    "#6c7086",
			Accent:       "#89b4fa",
			AccentHover:  "#74c7ec",
			Border:       "#45475a",
			Danger:       "#f38ba8",
			Success:      "#a6e3a1",
			Warning:      "#f9e2af",
			TabActive:    "#1e1e2e",
			TabInactive:  "#181825",
			BadgeColor:   "#f9e2af",
			ScrollTrack:  "#181825",
			ScrollThumb:  "#45475a",
		},
		Light: ThemeColors{
			BgPrimary:    "#eff1f5",
			BgSecondary:  "#e6e9ef",
			BgSurface:    "#ccd0da",
			BgHover:      "#bcc0cc",
			TextPrimary:  "#4c4f69",
			TextSecondary: "#5c5f77",
			TextMuted:    "#9ca0b0",
			Accent:       "#1e66f5",
			AccentHover:  "#209fb5",
			Border:       "#bcc0cc",
			Danger:       "#d20f39",
			Success:      "#40a02b",
			Warning:      "#df8e1d",
			TabActive:    "#eff1f5",
			TabInactive:  "#e6e9ef",
			BadgeColor:   "#df8e1d",
			ScrollTrack:  "#e6e9ef",
			ScrollThumb:  "#bcc0cc",
		},
	}
}

func nordTheme() Theme {
	return Theme{
		Name:        "nord",
		DisplayName: "Nord",
		BuiltIn:     true,
		Dark: ThemeColors{
			BgPrimary:    "#2e3440",
			BgSecondary:  "#272c36",
			BgSurface:    "#3b4252",
			BgHover:      "#434c5e",
			TextPrimary:  "#d8dee9",
			TextSecondary: "#c0c8d8",
			TextMuted:    "#616e88",
			Accent:       "#88c0d0",
			AccentHover:  "#8fbcbb",
			Border:       "#434c5e",
			Danger:       "#bf616a",
			Success:      "#a3be8c",
			Warning:      "#ebcb8b",
			TabActive:    "#2e3440",
			TabInactive:  "#272c36",
			BadgeColor:   "#ebcb8b",
			ScrollTrack:  "#272c36",
			ScrollThumb:  "#434c5e",
		},
		Light: ThemeColors{
			BgPrimary:    "#eceff4",
			BgSecondary:  "#e5e9f0",
			BgSurface:    "#d8dee9",
			BgHover:      "#c0c8d8",
			TextPrimary:  "#2e3440",
			TextSecondary: "#3b4252",
			TextMuted:    "#7b88a1",
			Accent:       "#5e81ac",
			AccentHover:  "#81a1c1",
			Border:       "#c0c8d8",
			Danger:       "#bf616a",
			Success:      "#a3be8c",
			Warning:      "#d08770",
			TabActive:    "#eceff4",
			TabInactive:  "#e5e9f0",
			BadgeColor:   "#d08770",
			ScrollTrack:  "#e5e9f0",
			ScrollThumb:  "#c0c8d8",
		},
	}
}

func tokyoNightTheme() Theme {
	return Theme{
		Name:        "tokyo-night",
		DisplayName: "Tokyo Night",
		BuiltIn:     true,
		Dark: ThemeColors{
			BgPrimary:    "#1a1b26",
			BgSecondary:  "#16161e",
			BgSurface:    "#24283b",
			BgHover:      "#33467c",
			TextPrimary:  "#c0caf5",
			TextSecondary: "#a9b1d6",
			TextMuted:    "#565f89",
			Accent:       "#7aa2f7",
			AccentHover:  "#7dcfff",
			Border:       "#33467c",
			Danger:       "#f7768e",
			Success:      "#9ece6a",
			Warning:      "#e0af68",
			TabActive:    "#1a1b26",
			TabInactive:  "#16161e",
			BadgeColor:   "#e0af68",
			ScrollTrack:  "#16161e",
			ScrollThumb:  "#33467c",
		},
		Light: ThemeColors{
			BgPrimary:    "#d5d6db",
			BgSecondary:  "#cbccd1",
			BgSurface:    "#b4b5b9",
			BgHover:      "#9699a3",
			TextPrimary:  "#343b58",
			TextSecondary: "#4c505e",
			TextMuted:    "#8990b3",
			Accent:       "#34548a",
			AccentHover:  "#166775",
			Border:       "#9699a3",
			Danger:       "#8c4351",
			Success:      "#485e30",
			Warning:      "#8f5e15",
			TabActive:    "#d5d6db",
			TabInactive:  "#cbccd1",
			BadgeColor:   "#8f5e15",
			ScrollTrack:  "#cbccd1",
			ScrollThumb:  "#9699a3",
		},
	}
}

func gruvboxTheme() Theme {
	return Theme{
		Name:        "gruvbox",
		DisplayName: "Gruvbox",
		BuiltIn:     true,
		Dark: ThemeColors{
			BgPrimary:    "#282828",
			BgSecondary:  "#1d2021",
			BgSurface:    "#3c3836",
			BgHover:      "#504945",
			TextPrimary:  "#ebdbb2",
			TextSecondary: "#d5c4a1",
			TextMuted:    "#7c6f64",
			Accent:       "#83a598",
			AccentHover:  "#8ec07c",
			Border:       "#504945",
			Danger:       "#fb4934",
			Success:      "#b8bb26",
			Warning:      "#fabd2f",
			TabActive:    "#282828",
			TabInactive:  "#1d2021",
			BadgeColor:   "#fabd2f",
			ScrollTrack:  "#1d2021",
			ScrollThumb:  "#504945",
		},
		Light: ThemeColors{
			BgPrimary:    "#fbf1c7",
			BgSecondary:  "#f2e5bc",
			BgSurface:    "#ebdbb2",
			BgHover:      "#d5c4a1",
			TextPrimary:  "#3c3836",
			TextSecondary: "#504945",
			TextMuted:    "#928374",
			Accent:       "#427b58",
			AccentHover:  "#79740e",
			Border:       "#d5c4a1",
			Danger:       "#9d0006",
			Success:      "#79740e",
			Warning:      "#b57614",
			TabActive:    "#fbf1c7",
			TabInactive:  "#f2e5bc",
			BadgeColor:   "#b57614",
			ScrollTrack:  "#f2e5bc",
			ScrollThumb:  "#d5c4a1",
		},
	}
}

func draculaTheme() Theme {
	return Theme{
		Name:        "dracula",
		DisplayName: "Dracula",
		BuiltIn:     true,
		Dark: ThemeColors{
			BgPrimary:    "#282a36",
			BgSecondary:  "#21222c",
			BgSurface:    "#44475a",
			BgHover:      "#555972",
			TextPrimary:  "#f8f8f2",
			TextSecondary: "#d4d4d4",
			TextMuted:    "#6272a4",
			Accent:       "#bd93f9",
			AccentHover:  "#ff79c6",
			Border:       "#44475a",
			Danger:       "#ff5555",
			Success:      "#50fa7b",
			Warning:      "#f1fa8c",
			TabActive:    "#282a36",
			TabInactive:  "#21222c",
			BadgeColor:   "#f1fa8c",
			ScrollTrack:  "#21222c",
			ScrollThumb:  "#44475a",
		},
		Light: ThemeColors{
			BgPrimary:    "#f8f8f2",
			BgSecondary:  "#f0f0e8",
			BgSurface:    "#e0e0d4",
			BgHover:      "#d0d0c4",
			TextPrimary:  "#282a36",
			TextSecondary: "#44475a",
			TextMuted:    "#8791b5",
			Accent:       "#7c3aed",
			AccentHover:  "#d6409f",
			Border:       "#d0d0c4",
			Danger:       "#dc2626",
			Success:      "#16a34a",
			Warning:      "#ca8a04",
			TabActive:    "#f8f8f2",
			TabInactive:  "#f0f0e8",
			BadgeColor:   "#ca8a04",
			ScrollTrack:  "#f0f0e8",
			ScrollThumb:  "#d0d0c4",
		},
	}
}

func oneDarkTheme() Theme {
	return Theme{
		Name:        "one-dark",
		DisplayName: "One Dark",
		BuiltIn:     true,
		Dark: ThemeColors{
			BgPrimary:    "#282c34",
			BgSecondary:  "#21252b",
			BgSurface:    "#353b45",
			BgHover:      "#3e4452",
			TextPrimary:  "#abb2bf",
			TextSecondary: "#9da5b4",
			TextMuted:    "#636d83",
			Accent:       "#61afef",
			AccentHover:  "#56b6c2",
			Border:       "#3e4452",
			Danger:       "#e06c75",
			Success:      "#98c379",
			Warning:      "#e5c07b",
			TabActive:    "#282c34",
			TabInactive:  "#21252b",
			BadgeColor:   "#e5c07b",
			ScrollTrack:  "#21252b",
			ScrollThumb:  "#3e4452",
		},
		Light: ThemeColors{
			BgPrimary:    "#fafafa",
			BgSecondary:  "#f0f0f0",
			BgSurface:    "#e0e0e0",
			BgHover:      "#d0d0d0",
			TextPrimary:  "#383a42",
			TextSecondary: "#4f525e",
			TextMuted:    "#a0a1a7",
			Accent:       "#4078f2",
			AccentHover:  "#0184bc",
			Border:       "#d0d0d0",
			Danger:       "#e45649",
			Success:      "#50a14f",
			Warning:      "#c18401",
			TabActive:    "#fafafa",
			TabInactive:  "#f0f0f0",
			BadgeColor:   "#c18401",
			ScrollTrack:  "#f0f0f0",
			ScrollThumb:  "#d0d0d0",
		},
	}
}

func catppuccinMacchiatoTheme() Theme {
	return Theme{
		Name:        "catppuccin-macchiato",
		DisplayName: "Catppuccin Macchiato",
		BuiltIn:     true,
		Dark: ThemeColors{
			BgPrimary:     "#24273a",
			BgSecondary:   "#1e2030",
			BgSurface:     "#363a4f",
			BgHover:       "#494d64",
			TextPrimary:   "#cad3f5",
			TextSecondary: "#a5adcb",
			TextMuted:     "#6e738d",
			Accent:        "#8aadf4",
			AccentHover:   "#91d7e3",
			Border:        "#494d64",
			Danger:        "#ed8796",
			Success:       "#a6da95",
			Warning:       "#eed49f",
			TabActive:     "#24273a",
			TabInactive:   "#1e2030",
			BadgeColor:    "#eed49f",
			ScrollTrack:   "#1e2030",
			ScrollThumb:   "#494d64",
		},
		Light: ThemeColors{
			BgPrimary:     "#eff1f5",
			BgSecondary:   "#e6e9ef",
			BgSurface:     "#ccd0da",
			BgHover:       "#bcc0cc",
			TextPrimary:   "#4c4f69",
			TextSecondary: "#5c5f77",
			TextMuted:     "#9ca0b0",
			Accent:        "#1e66f5",
			AccentHover:   "#209fb5",
			Border:        "#bcc0cc",
			Danger:        "#d20f39",
			Success:       "#40a02b",
			Warning:       "#df8e1d",
			TabActive:     "#eff1f5",
			TabInactive:   "#e6e9ef",
			BadgeColor:    "#df8e1d",
			ScrollTrack:   "#e6e9ef",
			ScrollThumb:   "#bcc0cc",
		},
	}
}

func solarizedTheme() Theme {
	return Theme{
		Name:        "solarized",
		DisplayName: "Solarized",
		BuiltIn:     true,
		Dark: ThemeColors{
			BgPrimary:    "#002b36",
			BgSecondary:  "#073642",
			BgSurface:    "#094959",
			BgHover:      "#1a5c6e",
			TextPrimary:  "#839496",
			TextSecondary: "#93a1a1",
			TextMuted:    "#586e75",
			Accent:       "#268bd2",
			AccentHover:  "#2aa198",
			Border:       "#1a5c6e",
			Danger:       "#dc322f",
			Success:      "#859900",
			Warning:      "#b58900",
			TabActive:    "#002b36",
			TabInactive:  "#073642",
			BadgeColor:   "#b58900",
			ScrollTrack:  "#073642",
			ScrollThumb:  "#1a5c6e",
		},
		Light: ThemeColors{
			BgPrimary:    "#fdf6e3",
			BgSecondary:  "#eee8d5",
			BgSurface:    "#ddd6c1",
			BgHover:      "#ccc5af",
			TextPrimary:  "#657b83",
			TextSecondary: "#586e75",
			TextMuted:    "#93a1a1",
			Accent:       "#268bd2",
			AccentHover:  "#2aa198",
			Border:       "#ccc5af",
			Danger:       "#dc322f",
			Success:      "#859900",
			Warning:      "#b58900",
			TabActive:    "#fdf6e3",
			TabInactive:  "#eee8d5",
			BadgeColor:   "#b58900",
			ScrollTrack:  "#eee8d5",
			ScrollThumb:  "#ccc5af",
		},
	}
}

func everforestTheme() Theme {
	return Theme{
		Name:        "everforest",
		DisplayName: "Everforest",
		BuiltIn:     true,
		Dark: ThemeColors{
			BgPrimary:     "#2d353b",
			BgSecondary:   "#272e33",
			BgSurface:     "#343f44",
			BgHover:       "#3d484d",
			TextPrimary:   "#d3c6aa",
			TextSecondary: "#c5b89a",
			TextMuted:     "#7a8478",
			Accent:        "#a7c080",
			AccentHover:   "#83c092",
			Border:        "#3d484d",
			Danger:        "#e67e80",
			Success:       "#a7c080",
			Warning:       "#dbbc7f",
			TabActive:     "#2d353b",
			TabInactive:   "#272e33",
			BadgeColor:    "#dbbc7f",
			ScrollTrack:   "#272e33",
			ScrollThumb:   "#3d484d",
		},
		Light: ThemeColors{
			BgPrimary:     "#fdf6e3",
			BgSecondary:   "#f4f0d9",
			BgSurface:     "#e5dfc5",
			BgHover:       "#d8d3ba",
			TextPrimary:   "#5c6a72",
			TextSecondary: "#708089",
			TextMuted:     "#a6b0a0",
			Accent:        "#8da101",
			AccentHover:   "#35a77c",
			Border:        "#d8d3ba",
			Danger:        "#f85552",
			Success:       "#8da101",
			Warning:       "#dfa000",
			TabActive:     "#fdf6e3",
			TabInactive:   "#f4f0d9",
			BadgeColor:    "#dfa000",
			ScrollTrack:   "#f4f0d9",
			ScrollThumb:   "#d8d3ba",
		},
	}
}

func ayuTheme() Theme {
	return Theme{
		Name:        "ayu",
		DisplayName: "Ayu",
		BuiltIn:     true,
		Dark: ThemeColors{
			BgPrimary:     "#0b0e14",
			BgSecondary:   "#0d1017",
			BgSurface:     "#11151c",
			BgHover:       "#1a1f29",
			TextPrimary:   "#bfbdb6",
			TextSecondary: "#acaaa1",
			TextMuted:     "#565b66",
			Accent:        "#e6b450",
			AccentHover:   "#ffb454",
			Border:        "#1a1f29",
			Danger:        "#d95757",
			Success:       "#7fd962",
			Warning:       "#e6b450",
			TabActive:     "#0b0e14",
			TabInactive:   "#0d1017",
			BadgeColor:    "#e6b450",
			ScrollTrack:   "#0d1017",
			ScrollThumb:   "#1a1f29",
		},
		Light: ThemeColors{
			BgPrimary:     "#fcfcfc",
			BgSecondary:   "#f3f3f3",
			BgSurface:     "#e7e8e9",
			BgHover:       "#d8d9da",
			TextPrimary:   "#5c6166",
			TextSecondary: "#787b80",
			TextMuted:     "#abb0b6",
			Accent:        "#f2ae49",
			AccentHover:   "#ff9940",
			Border:        "#d8d9da",
			Danger:        "#e65050",
			Success:       "#86b300",
			Warning:       "#f2ae49",
			TabActive:     "#fcfcfc",
			TabInactive:   "#f3f3f3",
			BadgeColor:    "#f2ae49",
			ScrollTrack:   "#f3f3f3",
			ScrollThumb:   "#d8d9da",
		},
	}
}

func kanagawaTheme() Theme {
	return Theme{
		Name:        "kanagawa",
		DisplayName: "Kanagawa",
		BuiltIn:     true,
		Dark: ThemeColors{
			BgPrimary:     "#1f1f28",
			BgSecondary:   "#16161d",
			BgSurface:     "#2a2a37",
			BgHover:       "#363646",
			TextPrimary:   "#dcd7ba",
			TextSecondary: "#c8c093",
			TextMuted:     "#727169",
			Accent:        "#7e9cd8",
			AccentHover:   "#7fb4ca",
			Border:        "#363646",
			Danger:        "#e82424",
			Success:       "#98bb6c",
			Warning:       "#e6c384",
			TabActive:     "#1f1f28",
			TabInactive:   "#16161d",
			BadgeColor:    "#e6c384",
			ScrollTrack:   "#16161d",
			ScrollThumb:   "#363646",
		},
		Light: ThemeColors{
			BgPrimary:     "#f2ecbc",
			BgSecondary:   "#e7dba0",
			BgSurface:     "#d9cea6",
			BgHover:       "#c9b97c",
			TextPrimary:   "#545464",
			TextSecondary: "#625e5a",
			TextMuted:     "#8a8980",
			Accent:        "#4d699b",
			AccentHover:   "#5a7785",
			Border:        "#c9b97c",
			Danger:        "#c84053",
			Success:       "#6f894e",
			Warning:       "#cc8c3c",
			TabActive:     "#f2ecbc",
			TabInactive:   "#e7dba0",
			BadgeColor:    "#cc8c3c",
			ScrollTrack:   "#e7dba0",
			ScrollThumb:   "#c9b97c",
		},
	}
}

func matrixTheme() Theme {
	return Theme{
		Name:        "matrix",
		DisplayName: "Matrix",
		BuiltIn:     true,
		Dark: ThemeColors{
			BgPrimary:     "#0d0d0d",
			BgSecondary:   "#080808",
			BgSurface:     "#1a1a1a",
			BgHover:       "#262626",
			TextPrimary:   "#00ff41",
			TextSecondary: "#00cc33",
			TextMuted:     "#338033",
			Accent:        "#00ff41",
			AccentHover:   "#33ff66",
			Border:        "#1a3a1a",
			Danger:        "#ff3333",
			Success:       "#00ff41",
			Warning:       "#ccff00",
			TabActive:     "#0d0d0d",
			TabInactive:   "#080808",
			BadgeColor:    "#ccff00",
			ScrollTrack:   "#080808",
			ScrollThumb:   "#1a3a1a",
		},
		Light: ThemeColors{
			BgPrimary:     "#f0fff0",
			BgSecondary:   "#e0f5e0",
			BgSurface:     "#c8e6c8",
			BgHover:       "#b0d9b0",
			TextPrimary:   "#0a3d0a",
			TextSecondary: "#1a5c1a",
			TextMuted:     "#6b9e6b",
			Accent:        "#008f11",
			AccentHover:   "#00b318",
			Border:        "#b0d9b0",
			Danger:        "#cc2222",
			Success:       "#008f11",
			Warning:       "#7a9900",
			TabActive:     "#f0fff0",
			TabInactive:   "#e0f5e0",
			BadgeColor:    "#7a9900",
			ScrollTrack:   "#e0f5e0",
			ScrollThumb:   "#b0d9b0",
		},
	}
}

func rosePineTheme() Theme {
	return Theme{
		Name:        "rose-pine",
		DisplayName: "Rosé Pine",
		BuiltIn:     true,
		Dark: ThemeColors{
			BgPrimary:     "#191724",
			BgSecondary:   "#1f1d2e",
			BgSurface:     "#26233a",
			BgHover:       "#2a283e",
			TextPrimary:   "#e0def4",
			TextSecondary: "#c4a7e7",
			TextMuted:     "#6e6a86",
			Accent:        "#c4a7e7",
			AccentHover:   "#ebbcba",
			Border:        "#2a283e",
			Danger:        "#eb6f92",
			Success:       "#31748f",
			Warning:       "#f6c177",
			TabActive:     "#191724",
			TabInactive:   "#1f1d2e",
			BadgeColor:    "#f6c177",
			ScrollTrack:   "#1f1d2e",
			ScrollThumb:   "#2a283e",
		},
		Light: ThemeColors{
			BgPrimary:     "#faf4ed",
			BgSecondary:   "#fffaf3",
			BgSurface:     "#f2e9e1",
			BgHover:       "#dfdad9",
			TextPrimary:   "#575279",
			TextSecondary: "#907aa9",
			TextMuted:     "#9893a5",
			Accent:        "#907aa9",
			AccentHover:   "#d7827e",
			Border:        "#dfdad9",
			Danger:        "#b4637a",
			Success:       "#286983",
			Warning:       "#ea9d34",
			TabActive:     "#faf4ed",
			TabInactive:   "#fffaf3",
			BadgeColor:    "#ea9d34",
			ScrollTrack:   "#fffaf3",
			ScrollThumb:   "#dfdad9",
		},
	}
}

func monokaiTheme() Theme {
	return Theme{
		Name:        "monokai",
		DisplayName: "Monokai",
		BuiltIn:     true,
		Dark: ThemeColors{
			BgPrimary:     "#272822",
			BgSecondary:   "#1e1f1c",
			BgSurface:     "#3e3d32",
			BgHover:       "#4e4d42",
			TextPrimary:   "#f8f8f2",
			TextSecondary: "#e0e0d8",
			TextMuted:     "#75715e",
			Accent:        "#66d9ef",
			AccentHover:   "#a6e22e",
			Border:        "#4e4d42",
			Danger:        "#f92672",
			Success:       "#a6e22e",
			Warning:       "#e6db74",
			TabActive:     "#272822",
			TabInactive:   "#1e1f1c",
			BadgeColor:    "#e6db74",
			ScrollTrack:   "#1e1f1c",
			ScrollThumb:   "#4e4d42",
		},
		Light: ThemeColors{
			BgPrimary:     "#fafafa",
			BgSecondary:   "#f0f0ec",
			BgSurface:     "#e0e0dc",
			BgHover:       "#d0d0cc",
			TextPrimary:   "#272822",
			TextSecondary: "#49483e",
			TextMuted:     "#9e9d89",
			Accent:        "#00a2c4",
			AccentHover:   "#669900",
			Border:        "#d0d0cc",
			Danger:        "#d31b5f",
			Success:       "#669900",
			Warning:       "#c4a500",
			TabActive:     "#fafafa",
			TabInactive:   "#f0f0ec",
			BadgeColor:    "#c4a500",
			ScrollTrack:   "#f0f0ec",
			ScrollThumb:   "#d0d0cc",
		},
	}
}

func catppuccinFrappeTheme() Theme {
	return Theme{
		Name:        "catppuccin-frappe",
		DisplayName: "Catppuccin Frappé",
		BuiltIn:     true,
		Dark: ThemeColors{
			BgPrimary:     "#303446",
			BgSecondary:   "#292c3c",
			BgSurface:     "#414559",
			BgHover:       "#51576d",
			TextPrimary:   "#c6d0f5",
			TextSecondary: "#b5bfe2",
			TextMuted:     "#949cb8",
			Accent:        "#8da4e2",
			AccentHover:   "#99b2ec",
			Border:        "#414559",
			Danger:        "#e78284",
			Success:       "#a6d189",
			Warning:       "#e5c890",
			TabActive:     "#303446",
			TabInactive:   "#292c3c",
			BadgeColor:    "#e5c890",
			ScrollTrack:   "#292c3c",
			ScrollThumb:   "#51576d",
		},
		Light: ThemeColors{
			BgPrimary:     "#eff1f5",
			BgSecondary:   "#e6e9ef",
			BgSurface:     "#ccd0da",
			BgHover:       "#bcc0cc",
			TextPrimary:   "#4c4f69",
			TextSecondary: "#5c5f77",
			TextMuted:     "#9ca0b0",
			Accent:        "#1e66f5",
			AccentHover:   "#2c74ff",
			Border:        "#bcc0cc",
			Danger:        "#d20f39",
			Success:       "#40a02b",
			Warning:       "#df8e1d",
			TabActive:     "#eff1f5",
			TabInactive:   "#e6e9ef",
			BadgeColor:    "#df8e1d",
			ScrollTrack:   "#e6e9ef",
			ScrollThumb:   "#bcc0cc",
		},
	}
}

func nightOwlTheme() Theme {
	return Theme{
		Name:        "night-owl",
		DisplayName: "Night Owl",
		BuiltIn:     true,
		Dark: ThemeColors{
			BgPrimary:     "#011627",
			BgSecondary:   "#01111d",
			BgSurface:     "#1d3b53",
			BgHover:       "#2a4a6b",
			TextPrimary:   "#d6deeb",
			TextSecondary: "#b8c4d4",
			TextMuted:     "#637777",
			Accent:        "#82aaff",
			AccentHover:   "#9ebfff",
			Border:        "#1d3b53",
			Danger:        "#ef5350",
			Success:       "#c5e478",
			Warning:       "#ecc48d",
			TabActive:     "#011627",
			TabInactive:   "#01111d",
			BadgeColor:    "#ecc48d",
			ScrollTrack:   "#01111d",
			ScrollThumb:   "#1d3b53",
		},
		Light: ThemeColors{
			BgPrimary:     "#f0f0f0",
			BgSecondary:   "#e5e5e5",
			BgSurface:     "#d4d4d4",
			BgHover:       "#c0c0c0",
			TextPrimary:   "#403f53",
			TextSecondary: "#575668",
			TextMuted:     "#7a8181",
			Accent:        "#4876d6",
			AccentHover:   "#5a88e8",
			Border:        "#d4d4d4",
			Danger:        "#de3d3b",
			Success:       "#2aa298",
			Warning:       "#c96765",
			TabActive:     "#f0f0f0",
			TabInactive:   "#e5e5e5",
			BadgeColor:    "#c96765",
			ScrollTrack:   "#e5e5e5",
			ScrollThumb:   "#c0c0c0",
		},
	}
}

func synthwave84Theme() Theme {
	return Theme{
		Name:        "synthwave-84",
		DisplayName: "Synthwave '84",
		BuiltIn:     true,
		Dark: ThemeColors{
			BgPrimary:     "#262335",
			BgSecondary:   "#1e1a30",
			BgSurface:     "#34294f",
			BgHover:       "#443566",
			TextPrimary:   "#ffffff",
			TextSecondary: "#e0d0f0",
			TextMuted:     "#848bbd",
			Accent:        "#36f9f6",
			AccentHover:   "#ff7edb",
			Border:        "#495495",
			Danger:        "#fe4450",
			Success:       "#72f1b8",
			Warning:       "#fede5d",
			TabActive:     "#262335",
			TabInactive:   "#1e1a30",
			BadgeColor:    "#fede5d",
			ScrollTrack:   "#1e1a30",
			ScrollThumb:   "#495495",
		},
		Light: ThemeColors{
			BgPrimary:     "#fafafa",
			BgSecondary:   "#f0f0f0",
			BgSurface:     "#e0e0e0",
			BgHover:       "#d0d0d0",
			TextPrimary:   "#262335",
			TextSecondary: "#3d3650",
			TextMuted:     "#5c5c8a",
			Accent:        "#00bcd4",
			AccentHover:   "#9c27b0",
			Border:        "#e0e0e0",
			Danger:        "#f44336",
			Success:       "#4caf50",
			Warning:       "#ff9800",
			TabActive:     "#fafafa",
			TabInactive:   "#f0f0f0",
			BadgeColor:    "#ff9800",
			ScrollTrack:   "#f0f0f0",
			ScrollThumb:   "#d0d0d0",
		},
	}
}

func cobalt2Theme() Theme {
	return Theme{
		Name:        "cobalt2",
		DisplayName: "Cobalt2",
		BuiltIn:     true,
		Dark: ThemeColors{
			BgPrimary:     "#193549",
			BgSecondary:   "#132d3e",
			BgSurface:     "#1f4662",
			BgHover:       "#2d5a7b",
			TextPrimary:   "#ffffff",
			TextSecondary: "#dde6ef",
			TextMuted:     "#adb7c9",
			Accent:        "#0088ff",
			AccentHover:   "#2affdf",
			Border:        "#2d5a7b",
			Danger:        "#ff0088",
			Success:       "#9eff80",
			Warning:       "#ffc600",
			TabActive:     "#193549",
			TabInactive:   "#132d3e",
			BadgeColor:    "#ffc600",
			ScrollTrack:   "#132d3e",
			ScrollThumb:   "#2d5a7b",
		},
		Light: ThemeColors{
			BgPrimary:     "#ffffff",
			BgSecondary:   "#f4f6f8",
			BgSurface:     "#e8ecf0",
			BgHover:       "#d3dae3",
			TextPrimary:   "#193549",
			TextSecondary: "#2e4a5e",
			TextMuted:     "#5c6b7d",
			Accent:        "#0066cc",
			AccentHover:   "#00acc1",
			Border:        "#d3dae3",
			Danger:        "#e91e63",
			Success:       "#4caf50",
			Warning:       "#ff9800",
			TabActive:     "#ffffff",
			TabInactive:   "#f4f6f8",
			BadgeColor:    "#ff9800",
			ScrollTrack:   "#f4f6f8",
			ScrollThumb:   "#d3dae3",
		},
	}
}

func githubTheme() Theme {
	return Theme{
		Name:        "github",
		DisplayName: "GitHub",
		BuiltIn:     true,
		Dark: ThemeColors{
			BgPrimary:     "#0d1117",
			BgSecondary:   "#090c10",
			BgSurface:     "#161b22",
			BgHover:       "#30363d",
			TextPrimary:   "#c9d1d9",
			TextSecondary: "#b1bac4",
			TextMuted:     "#8b949e",
			Accent:        "#58a6ff",
			AccentHover:   "#39c5cf",
			Border:        "#30363d",
			Danger:        "#f85149",
			Success:       "#3fb950",
			Warning:       "#e3b341",
			TabActive:     "#0d1117",
			TabInactive:   "#090c10",
			BadgeColor:    "#e3b341",
			ScrollTrack:   "#090c10",
			ScrollThumb:   "#30363d",
		},
		Light: ThemeColors{
			BgPrimary:     "#ffffff",
			BgSecondary:   "#f6f8fa",
			BgSurface:     "#f6f8fa",
			BgHover:       "#d0d7de",
			TextPrimary:   "#24292f",
			TextSecondary: "#3b424a",
			TextMuted:     "#57606a",
			Accent:        "#0969da",
			AccentHover:   "#1b7c83",
			Border:        "#d0d7de",
			Danger:        "#cf222e",
			Success:       "#1a7f37",
			Warning:       "#9a6700",
			TabActive:     "#ffffff",
			TabInactive:   "#f6f8fa",
			BadgeColor:    "#9a6700",
			ScrollTrack:   "#f6f8fa",
			ScrollThumb:   "#d0d7de",
		},
	}
}

func palenightTheme() Theme {
	return Theme{
		Name:        "palenight",
		DisplayName: "Palenight",
		BuiltIn:     true,
		Dark: ThemeColors{
			BgPrimary:     "#292d3e",
			BgSecondary:   "#232738",
			BgSurface:     "#3a3f58",
			BgHover:       "#4a4f6e",
			TextPrimary:   "#a6accd",
			TextSecondary: "#959bba",
			TextMuted:     "#676e95",
			Accent:        "#82aaff",
			AccentHover:   "#89ddff",
			Border:        "#3a3f58",
			Danger:        "#f07178",
			Success:       "#c3e88d",
			Warning:       "#ffcb6b",
			TabActive:     "#292d3e",
			TabInactive:   "#232738",
			BadgeColor:    "#ffcb6b",
			ScrollTrack:   "#232738",
			ScrollThumb:   "#3a3f58",
		},
		Light: ThemeColors{
			BgPrimary:     "#fafafa",
			BgSecondary:   "#f0f0f0",
			BgSurface:     "#eef0f4",
			BgHover:       "#dce0e8",
			TextPrimary:   "#292d3e",
			TextSecondary: "#3e4254",
			TextMuted:     "#8796b0",
			Accent:        "#4976eb",
			AccentHover:   "#00acc1",
			Border:        "#dce0e8",
			Danger:        "#e53935",
			Success:       "#91b859",
			Warning:       "#ffb300",
			TabActive:     "#fafafa",
			TabInactive:   "#f0f0f0",
			BadgeColor:    "#ffb300",
			ScrollTrack:   "#f0f0f0",
			ScrollThumb:   "#dce0e8",
		},
	}
}

func zenburnTheme() Theme {
	return Theme{
		Name:        "zenburn",
		DisplayName: "Zenburn",
		BuiltIn:     true,
		Dark: ThemeColors{
			BgPrimary:     "#3f3f3f",
			BgSecondary:   "#353535",
			BgSurface:     "#4f4f4f",
			BgHover:       "#5f5f5f",
			TextPrimary:   "#dcdccc",
			TextSecondary: "#c8c8b8",
			TextMuted:     "#9f9f9f",
			Accent:        "#8cd0d3",
			AccentHover:   "#93e0e3",
			Border:        "#5f5f5f",
			Danger:        "#cc9393",
			Success:       "#7f9f7f",
			Warning:       "#f0dfaf",
			TabActive:     "#3f3f3f",
			TabInactive:   "#353535",
			BadgeColor:    "#f0dfaf",
			ScrollTrack:   "#353535",
			ScrollThumb:   "#5f5f5f",
		},
		Light: ThemeColors{
			BgPrimary:     "#ffffef",
			BgSecondary:   "#f5f5e5",
			BgSurface:     "#efefdf",
			BgHover:       "#cfcfbf",
			TextPrimary:   "#3f3f3f",
			TextSecondary: "#525242",
			TextMuted:     "#6f6f6f",
			Accent:        "#5f7f8f",
			AccentHover:   "#5f8f8f",
			Border:        "#cfcfbf",
			Danger:        "#8f5f5f",
			Success:       "#5f8f5f",
			Warning:       "#8f8f5f",
			TabActive:     "#ffffef",
			TabInactive:   "#f5f5e5",
			BadgeColor:    "#8f8f5f",
			ScrollTrack:   "#f5f5e5",
			ScrollThumb:   "#cfcfbf",
		},
	}
}
